name: project_tugas_akhir
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dwds: ^16.0.1
  flutter:
    sdk: flutter
  form_field_validator: ^1.1.0
  get: 4.6.5
  hexcolor: ^3.0.1
  iconly: ^1.0.1
  responsive_framework: ^0.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/
    - assets/images/
  uses-material-design: true
